# Generated by Django 6.0 on 2026-02-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_users_email_verification_token_users_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email_verification_token',
        ),
    ]
