# Generated by Django 6.0 on 2026-02-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_users_email_verification_token'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
    ]
