# Generated by Django 6.0.2 on 2026-02-25 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("appointment_id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "appointments",
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("brand_id", models.AutoField(primary_key=True, serialize=False)),
                ("brand_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "brands",
            },
        ),
        migrations.CreateModel(
            name="InventoryCategory",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "inventory_categories",
            },
        ),
        migrations.CreateModel(
            name="JobVacancy",
            fields=[
                ("vacancy_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mechanic", "Mechanic"),
                            ("assistant", "Assistant"),
                            ("reception", "Reception"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("openings", models.PositiveIntegerField(default=1)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("description", models.TextField()),
                ("requirements", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "job_vacancies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                ("part_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                (
                    "compatible_model",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("min_stock_level", models.PositiveIntegerField(default=5)),
                ("image", models.ImageField(blank=True, null=True, upload_to="parts/")),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="adminpanel.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="adminpanel.inventorycategory",
                    ),
                ),
            ],
            options={
                "db_table": "parts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkList",
            fields=[
                ("work_list_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "job_status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminpanel.appointment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "work_list",
                "ordering": ["-created_at"],
            },
        ),
    ]
