# Generated by Django 6.0.2 on 2026-02-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                ("vacancy_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mechanic", "Mechanic"),
                            ("washing", "Car Washing"),
                            ("accountant", "Accountant"),
                            ("receptionist", "Receptionist"),
                            ("manager", "Service Manager"),
                            ("helper", "Helper"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("requirements", models.TextField(blank=True)),
                ("openings", models.PositiveIntegerField(default=1)),
                ("deadline", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "vacancy",
                "ordering": ["-created_at"],
            },
        ),
    ]
